name: SSE Editor Release

on:
  push:
    tags: "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      # - run: num ci

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm install typescript -D
      - run: npm run build
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  release:
    needs: publish
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      actions: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Version
        id: version
        run: |
          tag=${GITHUB_REF/refs\/tags\//}
          version=${tag#v}
          major=${version%%.*}
          echo "tag=${tag}" >> $GITHUB_OUTPUT
          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "major=${major}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: release-drafter/release-drafter@master
        with:
          version: ${{steps.version.outputs.version}}
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Force Update Major Tag
      #   run: |
      #     git tag v${{ steps.version.outputs.major }} ${{ steps.version.outputs.tag }} -f
      #     git push origin refs/tags/v${{ steps.version.outputs.major }} -f

      - name: Tag the release
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "github-actions@github.com"
          git tag v${{ github.sha }}
          git push origin refs/tags/v${{ github.sha }}
